### ISSUE TITLE
grab object and move player question

### ISSUE THREAD

**Issue by fingerx** [JScott/ViveGrip#13]
When using Controller grab object and using other Controller move player（myself avatar）,The object fell off and did not move with the player. what should I do? thanks！

**Comment by JScott** [comment]
How did you move the player? Held objects will automatically drop when they go beyond the [configurable hold radius](https://github.com/JScott/ViveGrip/blob/master/Assets/ViveGrip/Scripts/Prefab/ViveGrip_GripPoint.cs#L8-L9).

Sudden movements, like teleporting, will require moving the object with the player to avoid going outside that distance. Depending on your use case, you might also try bumping up that threshold.

**Comment by fingerx** [comment]
ok
thanks!
